// Generated by Boemia Script Compiler
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

int main(void) {
    char* mensaje = "Hola, Boemia Script!";
    printf("%s\n", mensaje);
    return 0;
}
